version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5


  backend:
    build:
      context: ./vsu-canteen-backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env
    ports:
      - "80:8000"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./vsu-canteen/food-ordering-app
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend


volumes:
  pg_data: